### ISSUE TITLE
Variable and function names

### ISSUE THREAD

**Issue by shiryz** [facn5/shajaraWebSolutions#28]
You need to name your variables in a better and more meaningful way 
Something that makes it clear what they do and what is the purpose of them
For example
`myFunction` : https://github.com/facn5/shajaraWebSolutions/blob/master/script.js#L31
`(e)`: https://github.com/facn5/shajaraWebSolutions/blob/master/script.js#L1

**Comment by ghost** [comment]
myFunction renamed to onScrollShowNavBar
e renamed to element
