### ISSUE TITLE
Tidy up indentation

### ISSUE THREAD

**Issue by msachi** [facn5/shajaraWebSolutions#29]
For example here, but in lots of places:
https://github.com/facn5/shajaraWebSolutions/blob/400398ac163e4295b4568518294c525a263bd499/style.css#L46

I suggest using only spaces and not tabs (you can set your code editor so that when you press tab it will insert 2 spaces instead). Otherwise if you have a mix of tabs and spaces this will come out messy on Github and is difficult to view / review.

**Comment by ghost** [comment]
Issue fixed, everything is sorted out by tabs.
