### ISSUE TITLE
links to LinkedIn, GitHub, and CodeWars on team profiles

### ISSUE THREAD

**Issue by misterrodger** [facn5/shajaraWebSolutions#6]

**Comment by misterrodger** [comment]
![2012-02-11_21-27-41_276](https://user-images.githubusercontent.com/32282170/53876885-75b59680-4010-11e9-9d27-de8ac98be8fc.jpg)

**Comment by karam1ashqar** [comment]
Those are mine:-
Github:- https://github.com/karam1ashqar
LinkedIn: https://www.linkedin.com/in/karam-ashqar-8b96ba181/
Codewars: https://codewars.com/users/karam1ashqar
